mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('django.contrib.auth.urls'))
]

mysite/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('mypolls/', views.MyPollsView.as_view(), name='mypolls'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('create/', views.CreatePollView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.UpdatePollView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.DeletePollView.as_view(), name='delete'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class CustomUser(AbstractUser):
    about = models.CharField(max_length=200, default='', blank=True)

    def __str__(self):
        return self.email


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    # voters = models.ManyToManyField(CustomUser)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Question, Choice


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email', 'about')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'about')


# class QuestionForm(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = ('question_text', 'owner')


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice_text',)


CreatePollFormSet = inlineformset_factory(
    Question, Choice, form=ChoiceForm, extra=1)

mysite/polls/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone


from .models import Question, Choice
from .forms import CustomUserCreationForm, CreatePollFormSet


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those
        to be published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class MyPollsView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/mypolls.html'
    context_object_name = "question_list"

    def get_queryset(self):
        """
        Return the list of all polls owned by logged in user.
        """
        return Question.objects.filter(
            owner=self.request.user.id
        ).order_by('-pub_date')


class SearchView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'polls/search.html'
    model = Question

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data(*args, **kwargs)
        question_text = self.request.GET.get('q', '')

        if question_text != '':
            question_list = self.model.objects.filter(
                question_text__icontains=question_text)
            context['q'] = question_text
        else:
            question_list = self.model.objects.all()

        context['question_list'] = question_list
        return context


class CreatePollView(LoginRequiredMixin, generic.CreateView):
    model = Question
    fields = ['question_text']
    success_url = reverse_lazy('polls:mypolls')
    template_name = 'polls/create_poll.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_owner'] = True
        if self.request.POST:
            context['choices'] = CreatePollFormSet(self.request.POST)
        else:
            context['choices'] = CreatePollFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        choices = context['choices']
        form.instance.owner = self.request.user
        with transaction.atomic():
            self.object = form.save()

            if choices.is_valid():
                choices.instance = self.object
                choices.save()
        # why do we need to use super(...) instead of super()
        return super(CreatePollView, self).form_valid(form)


class UpdatePollView(LoginRequiredMixin, generic.UpdateView):
    model = Question
    fields = ['question_text', 'owner']
    success_url = reverse_lazy('polls:mypolls')
    template_name = 'polls/create_poll.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.object.owner == self.request.user:
            context['is_owner'] = True

            if self.request.POST:
                context['choices'] = CreatePollFormSet(
                    self.request.POST, instance=self.object)
            else:
                context['choices'] = CreatePollFormSet(instance=self.object)
        else:
            context['is_owner'] = False
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        choices = context['choices']
        with transaction.atomic():
            self.object = form.save()

            if choices.is_valid():
                choices.instance = self.object
                choices.save()
        return super(UpdatePollView, self).form_valid(form)


class DeletePollView(LoginRequiredMixin, generic.DeleteView):
    model = Question
    success_url = reverse_lazy('polls:mypolls')
    template_name = 'polls/confirm_delete.html'

    # there should be another way to do it (and show message or return HttpResponseForbidden)
    # def get_queryset(self):
    #     owner = self.request.user
    #     return self.model.objects.filter(owner=owner)

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super().get_object()
        if not obj.owner == self.request.user:
            raise PermissionDenied
        return obj


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = "polls/results.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super().get_object()
        if not obj.owner == self.request.user:
            raise PermissionDenied
        return obj


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  {% comment %} {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"> {% endcomment %}
</head>
<body>
  <div id="content" class="container">
    {% if user.is_authenticated %}
      <p><a href="{% url 'polls:mypolls' %}">My Polls</a> | <a href="#">History</a> | <a href="{% url 'polls:index' %}">Recent Polls</a> | <a href="{% url 'polls:search' %}">Search</a> | <a href="{% url 'logout' %}">Logout</a></p>
    {% endif %}

    <div class="md-col-10">
      {% block content %}{% endblock %}
    </div>
  </div>
</body>
</html>

mysite/polls/templates/polls/confirm_delete.html
{% extends 'polls/base.html' %}

{% block title %}Poll delete{% endblock %}


{% block content %}
  <h1></h1>
  <hr>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input type="submit" value="Confirm"/>
    </form>
  </div>
{% endblock %}

mysite/polls/templates/polls/create_poll.html
{% extends 'polls/base.html' %}
{% load static %}

{% block title %}Create a poll{% endblock %}

{% block content %}
    {% if is_owner %}
    <h1>Poll</h1>
        <hr>
        <div class="col-md-4">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}

                <table class="table">
                    {{ choices.management_form }}

                    {% for form in choices.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th>{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr class="{% cycle row1 row2 %} formset_row">
                            {% for field in form.visible_fields %}
                                <td>
                                    {# Include the hidden fields in the form #}
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
                <input type="submit" value="Save"/> <a href="{% url 'polls:mypolls' %}">back to the list</a>
            </form>
        </div>
        <script
            src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
        <script src="{% static 'formset/jquery.formset.js' %}"></script>
        <script type="text/javascript">
            $('.formset_row').formset({
                addText: 'add choice',
                deleteText: 'remove',
                prefix: 'choice_set'
            });
        </script>
    {% else %}
        <p>You are not the owner of this poll</p>
        <a href="{% url 'polls:mypolls' %}">back to the list</a>
    {% endif %}
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}Poll details{% endblock %}

{% block content %}
<h1>{{ question.question_text }}</h1>
<p>Owner: {{ question.owner }}</p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <p>
      <input 
        type="radio" 
        name="choice" 
        id="choice{{ forloop.counter }}" 
        value="{{ choice.id }}"
      />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}<label>
    </p>
  {% endfor %}
  <input type="submit" value="Vote">
</form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <p>Hi {{ user.username }}!</p>
  {% comment %} <p><a href="{% url 'polls:mypolls' %}">My Polls</a> | History | <a href="{% url 'logout' %}">Logout</a></p>  {% endcomment %}
  {% if latest_question_list %}
    <h1>Recent Polls:</h1>
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No polls are available.</p>
  {% endif %}
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> |
  <a href="{% url 'polls:signup' %}">signup</a>
{% endif %}
{% endblock %}

mysite/polls/templates/polls/mypolls.html
{% extends 'polls/base.html' %}

{% block title %}My Polls{% endblock %}

{% block content %}
<h1>My Polls</h1>
<ul>
  {% for question in question_list %}
    <li>
      <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> | <a href="{% url 'polls:edit' question.id %}">edit</a> <a href="{% url 'polls:delete' question.id %}">delete</a>
    </li>
  {% endfor %}
</ul>
<p><a href="{% url 'polls:create' %}">add a poll</a></p>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}Poll results{% endblock %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href={% url 'polls:detail' question.id %}>Vote again?</a>
{% endblock %}

mysite/polls/templates/polls/search.html
{% extends 'polls/base.html' %}

{% block title %}Poll search{% endblock %}

{% block content %}
<h1>Poll Search</h1>

<form action="" method="get">
  {% comment %} Is it ok to use GET without csrf_token {% endcomment %}
  {% comment %} {% csrf_token %} {% endcomment %}
  <input 
        type="text" 
        name="q" 
        id="q" 
        value="{{ q }}"
      />
  <input type="submit" value="Search">
</form>

<ul>
  {% for question in question_list %}
    <li>
      <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </li>
  {% endfor %}
</ul>
{% endblock %}